### ISSUE TITLE
Why not use https://github.com/DavBfr/dart_pdf ?

### ISSUE THREAD

**Issue by gedw99** [PSPDFKit/pspdfkit-flutter#15]
I see little difference but maybe i am missing the smaller details ?

dart_pdf requires you to write custom rendering for each widget to output PDF. Maybe yours is smarter?

**Comment by gedw99** [comment]
Oh yours is closed binary dependency ?

**Comment by steipete** [comment]
This repository wraps the commercial PSPDFKit SDK for iOS and Android.

Here's all the features we offer:
https://pspdfkit.com/pdf-sdk/ios/
https://pspdfkit.com/pdf-sdk/android/
