### ISSUE TITLE
PDF File Security

### ISSUE THREAD

**Issue by hasimyerlikaya** [PSPDFKit/pspdfkit-flutter#17]
Hi, 

We are thinking use your product in our mobile app.
We must open secure pdf file with password. 
Can you implement security options? 
After that we will buy a license.

**Comment by radazzouz** [comment]
@hasimyerlikaya,

We started implementing the ability to unlock password protected documents in #18.

Note that the pull request is still work in progress, but so far it is functional on iOS, so you can test it right away.

Please let us know if this helps you unlock your password protected documents.

Thanks again!
