### ISSUE TITLE
com.pspdfkit.ui.LocalizedTextView Not found

### ISSUE THREAD

**Issue by SHRJamal** [PSPDFKit/pspdfkit-flutter#41]
Hi!
I get a crash with this info, hope get some help:
java.lang.RuntimeException: Unable to start activity ComponentInfo{'packagename'/com.pspdfkit.ui.PdfActivity}: android.view.InflateException: Binary XML file line #57: Binary XML file line #57: Error inflating class com.pspdfkit.ui.LocalizedTextView

**Comment by simoarpe** [comment]
Jamal,
my apologies for the belated answer. 
Can you make sure you are using the latest changes from master?
Are you able to reproduce the crash using the [Flutter Example project](https://github.com/PSPDFKit/pspdfkit-flutter/tree/master/example)?

Please run `flutter doctor` and `flutter --version` and make sure the latest versions for all the components are correctly installed.
To date, you should have a similar configuration:
<img width="797" alt="fish__Users_sarpex__fish_" src="https://user-images.githubusercontent.com/3308503/72615849-e36f6600-3935-11ea-9c61-ac2769b2b908.png">

Let me know if it solves the issue.

**Comment by SHRJamal** [comment]
I tested the library for a long time now, my trial is ended and I can't run it anymore, so you can close the issue.
