### ISSUE TITLE
Pages on screen

### ISSUE THREAD

**Issue by yadaniyil** [PSPDFKit/pspdfkit-flutter#45]
Is it possible to specify the number of PDF pages to show on the screen at one time?

**Comment by radazzouz** [comment]
@yadaniyil,

Thanks for reaching out to us!

I've just exposed the page layout mode configuration option on iOS in #46. The Android implementation will come soon.

Let me know if this helps you with your use case.

Have a great weekend!

**Comment by yadaniyil** [comment]
@radazzouz 

Thank you for quick response and implementation.
Waiting for android to use it in the app!

**Comment by yadaniyil** [comment]
Hey @radazzouz.

Also, in Android I can press on appbar settings button and I'll have pages layout options (1 page, 2 pages, auto). 
![image](https://user-images.githubusercontent.com/16175106/68464545-75157580-0219-11ea-87a8-ae4780e8446b.png)
Is there the same feature in iOS?

**Comment by aksh1t** [comment]
Hey @yadaniyil !

I have just updated this PR to also include customizability for the iOS settings button like you requested above.

Check out the changes in the PR in the `main.dart` file. You can use the `iOSSettingsMenuItems` option with `pageMode` to get the same menu in iOS. To position the settings menu item on the left or right side of the navigation bar, use this option: `iOSLeftBarButtonItems:['settingsButtonItem']` or `iOSRightBarButtonItems:['settingsButtonItem']`. 

I hope this helps!

**Comment by radazzouz** [comment]
Fixed by #46. Closing.
