### ISSUE TITLE
How can i disable some feature?

### ISSUE THREAD

**Issue by hasimyerlikaya** [PSPDFKit/pspdfkit-flutter#8]
Hi, thank you for this good product.
I like it very much and maybe we can use in our flutter product.
But I think we are need disable some feature. How can i do this?

**Comment by steipete** [comment]
Hi! Feel free to drop us a ticket via https://pspdfkit.com/support/request/ with more details on the features you'd like to disable. PSPDFKit is highly configurable, just not everything is exposed via Flutter just yet. 

Thanks!
